name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_PUBHUB_USER }}
        password: ${{ secrets.DOCKER_PUBHUB_PASS }}
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ldxw/openlist:api_server

    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile-Lite
        push: false
        tags: ldxw/openlist:api_server_alpine

    - name: Push Docker Image to ghcrio
      run:     docker push ldxw/openlist:api_server
            && docker tag  ldxw/openlist:api_server ghcr.io/ldxw/openlist:api_server
            && docker push ghcr.io/ldxw/openlist:api_server

    - name: Push Docker Image to ghcrio
      run:     docker push ldxw/openlist:api_server_alpine
            && docker tag  ldxw/openlist:api_server_alpine ghcr.io/ldxw/openlist:api_server_alpine
            && docker push ghcr.io/ldxw/openlist:api_server_alpine
